# Generated by Django 4.2.7 on 2026-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ent_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
