# Generated by Django 4.2.7 on 2026-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
