# Generated by Django 4.2.7 on 2026-06-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_assessment_sended_date_attendance_sended_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_url', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'SMS sozlamalari',
            },
        ),
    ]
